import type { Metadata } from 'next';
import { Inter, Belanosima } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const belanosima = Belanosima({
  subsets: ['latin'],
  weight: ['600', '400', '700'],
  variable: '--font-belanosima',
});

export const metadata: Metadata = {
  title: 'Maharesigana',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${belanosima.variable}`}>
        {children}
      </body>
    </html>
  );
}
